version: '3.8'

services:
  lab1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/flask-app_lab1:latest
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
    - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
    ports:
      - "5000:5000"