name: "Lab1: Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image to GHCR
        env:
          IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/flask-app:latest"
        run: |
          cd lab1
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  # Step 2: Run Job
  run:
    runs-on: [self-hosted]
    needs: build  # Ensures `run` job only starts after `build` job completes

    steps:
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and Run Docker Image from GHCR
        env:
          IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/flask-app:latest"
        run: |
          docker pull $IMAGE_NAME
          docker run -d -p 5000:5000 $IMAGE_NAME
