name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
      labels: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions for script
        run: chmod +x ./lab1/flaskapp/st.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask
          pip install gunicorn
          pip install requests

      - name: Run script
        run: |
          cd ./lab1/flaskapp
          ./st.sh
